# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

appearance:
  mode: system
  color: indigo

marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: ""
    description: "The highly-customizable Hugo Academic theme powered by Hugo Blox Builder."
    twitter: "GetResearchDev"
  analytics:
    google_analytics: ""
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""
    baidu: ""

header:
  navbar:
    enable: true
    block: "navbar"
    align: "left"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Michael C. Quinn"

footer:
  copyright:
    notice: "© {year} Me. This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

features:
  math:
    enable: false
  privacy_pack:
    enable: false

# Load /assets/css/custom.css
assets:
  css:
    - "css/custom.css"
    
favicon:
  logo: "favicon.png"
custom_css:
  - css/custom.css
